-- MySQL Script generated by MySQL Workbench
-- sáb 15 mai 2021 17:33:30 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reputacao_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reputacao_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reputacao_service` DEFAULT CHARACTER SET utf8 ;
USE `reputacao_service` ;

-- -----------------------------------------------------
-- Table `reputacao_service`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reputacao_service`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login_usuario` VARCHAR(45) NOT NULL,
  `nome_completo` VARCHAR(100) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reputacao_service`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reputacao_service`.`projetos` (
  `projeto_id` INT(11) NOT NULL AUTO_INCREMENT,
  `projeto_nome` VARCHAR(100) NOT NULL,
  `chave` VARCHAR(255) NOT NULL,
  `projeto_img` VARCHAR(200) NULL,
  `projeto_descricao` VARCHAR(45) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`projeto_id`, `id_usuario`),
  INDEX `fk_projetos_usuarios1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_projetos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `reputacao_service`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `reputacao_service`.`tipo_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reputacao_service`.`tipo_avaliacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `reputacao_service`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reputacao_service`.`avaliacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nota` INT(11) NOT NULL,
  `item` INT(11) NOT NULL,
  `data` DATETIME NOT NULL,
  `tipo` INT(11) NOT NULL,
  `projeto_id` INT(11) NOT NULL,
  `tipo_item` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Avaliacao_tipoAvaliacao1_idx` (`tipo` ASC) ,
  INDEX `fk_avaliacao_projetos1_idx` (`projeto_id` ASC) ,
  CONSTRAINT `fk_Avaliacao_tipoAvaliacao1`
    FOREIGN KEY (`tipo`)
    REFERENCES `reputacao_service`.`tipo_avaliacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_projetos1`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `reputacao_service`.`projetos` (`projeto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getNota`(IN item INT, IN projeto INT, IN tipoavaliacao INT)
BEGIN
             IF tipoavaliacao = 1 THEN
             SELECT COUNT(*) FROM avaliacao WHERE nota = 5 AND avaliacao.item = item AND avaliacao.projeto_id = projeto AND tipo = 1 into @nota5;
             SELECT COUNT(*) FROM avaliacao WHERE nota = 4 AND avaliacao.item = item AND avaliacao.projeto_id = projeto AND tipo = 1 into @nota4;
             SELECT COUNT(*) FROM avaliacao WHERE nota = 3 AND avaliacao.item = item AND avaliacao.projeto_id = projeto AND tipo = 1 into @nota3;
             SELECT COUNT(*) FROM avaliacao WHERE nota = 2 AND avaliacao.item = item  AND avaliacao.projeto_id = projeto AND tipo = 1 into @nota2;
             SELECT COUNT(*) FROM avaliacao WHERE nota = 1 AND avaliacao.item = item AND avaliacao.projeto_id = projeto AND tipo = 1 into @nota1;
             SELECT @nota1 AS qtd_nota1, @nota2 AS qtd_nota2, @nota3 AS qtd_nota3, @nota4 AS qtd_nota4, @nota5 AS qtd_nota5;
             END IF;

             IF tipoavaliacao = 2 THEN
            SELECT COUNT(*) FROM avaliacao WHERE nota = 1 AND avaliacao.item = item AND avaliacao.projeto_id = projeto AND avaliacao.item = item AND tipo = 2 into @like;
             SELECT COUNT(*) FROM avaliacao WHERE nota = 0 AND avaliacao.item = item AND avaliacao.item = item AND avaliacao.projeto_id = projeto AND tipo = 2 into @dislike;
        
            SELECT @like AS qtd_like, @dislike AS qtd_dislike;
           END IF;
    END$$
DELIMITER ;

INSERT INTO `tipo_avaliacao` (`id`, `descricao`) VALUES (NULL, 'five-stars');
INSERT INTO `tipo_avaliacao` (`id`, `descricao`) VALUES (NULL, 'like-dislike');
INSERT INTO `tipo_avaliacao` (`id`, `descricao`) VALUES (NULL, 'slider');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
